platform :ios, '16.0'
use_frameworks!

target 'ManufacturingAI' do
    # Meta Wearables SDK (Device Access Toolkit)
    pod 'MetaWearablesSDK', '~> 1.0'
    
    # Google Generative AI (Gemini)
    pod 'GoogleGenerativeAI', '~> 0.5'
    
    # Networking
    pod 'Alamofire', '~> 5.8'
    
    # Image processing
    pod 'SDWebImageSwiftUI', '~> 2.2'
    
    # Development helpers
    pod 'SwiftLint'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.0'
        end
    end
end
